package com.mcy.define;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mcy.define.MeiZi;

import com.mcy.define.MeiZiDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig meiZiDaoConfig;

    private final MeiZiDao meiZiDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        meiZiDaoConfig = daoConfigMap.get(MeiZiDao.class).clone();
        meiZiDaoConfig.initIdentityScope(type);

        meiZiDao = new MeiZiDao(meiZiDaoConfig, this);

        registerDao(MeiZi.class, meiZiDao);
    }
    
    public void clear() {
        meiZiDaoConfig.clearIdentityScope();
    }

    public MeiZiDao getMeiZiDao() {
        return meiZiDao;
    }

}
